server:
  port: 1201

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-service/**

        - id: product-history-service
          uri: lb://PRODUCT-HISTORY-SERVICE
          predicates:
            - Path=/product-history-service/**

        - id: stock-service
          uri: lb://STOCK-SERVICE
          predicates:
            - Path=/stock-service/**

        - id: stock-history-service
          uri: lb://STOCK-HISTORY-SERVICE
          predicates:
            - Path=/stock-history-service/**

        - id: eureka-server
          uri: http://localhost:8761
          predicates:
            - Path=Path=/eureka/web
          filters:
            - SetPath=/

        - id: eureka-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
