server:
  port: 1205
  servlet:
    context-path: /product-service
spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/stockmanagement
  kafka:
    consumer:
      auto-offset-reset: earliest
kafka:
  topic:
    product:
      history: cmd.entity.product
      update: cmd.update.product
    stock:
      add: cmd.product.stock

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka