server:
  port: 1208
  servlet:
    context-path: /stock-history-service
spring:
  application:
    name: stock-history-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/stockmanagement
  kafka:
    consumer:
      auto-offset-reset: earliest

kafka:
  topic:
    stock:
      history: cmd.entity.stock

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka